#!/usr/bin/env bash
# Do not change file directly, changes will be overwritten.
#

# when creating a certificate for a site for the first time, run the following command first.
#
#  certbot certonly --standalone -d www.somesite.com --non-interactive --agree-tos --email your_address@email.com --http-01-port=8888
#
# After the initial certificate request, you can add the site to the list of sites in the '/etc/letsencrypt/sites.list' file.

# Renew the certificate
#certbot renew --force-renewal --preferred-challenges http
certbot renew --preferred-challenges http

# cleanup haproxy certificate list temp file
if test -f /tmp/certificate.list; then rm /tmp/certificate.list; fi

# create new haproxy certificate list temp file
touch /tmp/certificate.list

# for site in /etc/letsencrypt/sites.list...
for site in $(grep -vE '(^#|^$)' /etc/letsencrypt/sites.list); do
        # create directories required
        mkdir -p /etc/ssl/${site}/

        # Concatenate new cert files
        bash -c "cat /etc/letsencrypt/live/${site}/fullchain.pem /etc/letsencrypt/live/${site}/privkey.pem > /etc/ssl/${site}/${site}.pem"

	# update the haproxy certificate.list file
	echo "/etc/haproxy/tls/${site}/${site}.pem" >> /tmp/certificate.list

	# send files to: dmzhalb1
	ssh root@dmzhalb1 mkdir -p /etc/haproxy/tls/${site}
	scp /etc/ssl/${site}/${site}.pem root@dmzhalb1:/etc/haproxy/tls/${site}/
	scp /tmp/certificate.list root@dmzhalb1:/etc/haproxy/tls/certificate.list
	
	# send files to: dmzhalb2
	ssh root@dmzhalb2 mkdir -p /etc/haproxy/tls/${site}
	scp /etc/ssl/${site}/${site}.pem root@dmzhalb2:/etc/haproxy/tls/${site}/
	scp /tmp/certificate.list root@dmzhalb2:/etc/haproxy/tls/certificate.list

	# send files to: hlb01.dmz.unkin.net
	ssh root@10.10.8.36 mkdir -p /etc/haproxy/tls/${site}
	scp /etc/ssl/${site}/${site}.pem root@10.10.8.36:/etc/haproxy/tls/${site}/
	scp /tmp/certificate.list root@10.10.8.36:/etc/haproxy/tls/certificate.list
	
	# send files to: hlb02.dmz.unkin.net
	ssh root@10.10.8.37 mkdir -p /etc/haproxy/tls/${site}
	scp /etc/ssl/${site}/${site}.pem root@10.10.8.37:/etc/haproxy/tls/${site}/
	scp /tmp/certificate.list root@10.10.8.37:/etc/haproxy/tls/certificate.list
done

# run post-processing commands
ssh root@dmzhalb1 systemctl restart haproxy
ssh root@dmzhalb2 systemctl restart haproxy
#ssh root@10.10.8.36 systemctl restart haproxy
#ssh root@10.10.8.37 systemctl restart haproxy
